lib_name = "DevolutionsIronRdp"

[dotnet]
namespace = "Devolutions.IronRdp"
native_lib = "DevolutionsIronRdp"
exception_trim_suffix = "Error"
exception_message_method = "ToDisplay"

setters_prefix = "set_"
getters_prefix = "get_"
