
defalt: bindings

dotnet_generated_path := "./dotnet/Devolutions.IronRdp/Generated/"
dotnet_diplomat_config := "./dotnet-interop-conf.toml"

dotnet_dll_name := "DevolutionsIronRdp.dll"
rust_built_dll_name := "ironrdp.dll"

rust_build_result_diretory := "../target/debug/"

bindings:
    -rm {{dotnet_generated_path}}*.cs
    diplomat-tool dotnet {{dotnet_generated_path}} -l {{dotnet_diplomat_config}}
    @echo ">> .NET wrapper generated at {{dotnet_generated_path}}"

build-dll:
    cargo build
    cp {{rust_build_result_diretory}}{{rust_built_dll_name}} {{rust_build_result_diretory}}{{dotnet_dll_name}}