[package]
name = "ironrdp-dvc-pipe-proxy"
version = "0.1.0"
readme = "README.md"
description = "DVC named pipe proxy for IronRDP"
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
authors.workspace = true
keywords.workspace = true
categories.workspace = true

[lib]
doctest = false
test = false

[dependencies]
ironrdp-core = { path = "../ironrdp-core", version = "0.1" }
ironrdp-pdu = { path = "../ironrdp-pdu", version = "0.5" } # public (PduResult type)
ironrdp-dvc = { path = "../ironrdp-dvc", version = "0.3" }
ironrdp-svc = { path = "../ironrdp-svc", version = "0.4" } # public (SvcMessage type)

tracing = { version = "0.1", features = ["log"] }

[target.'cfg(windows)'.dependencies]
widestring = "1"
windows = { version = "0.61", features = [
    "Win32_Foundation",
    "Win32_Security",
    "Win32_System_Threading",
    "Win32_Storage_FileSystem",
    "Win32_System_Pipes",
    "Win32_System_IO",
] }

[lints]
workspace = true
