[package]
name = "ironrdp-pdu-generators"
version = "0.0.0"
description = "`proptest` generators for `ironrdp-pdu` types"
publish = false
edition.workspace = true

[lib]
doctest = false
test = false

[dependencies]
# ironrdp-pdu.workspace = true
# proptest.workspace = true

[lints]
workspace = true

