[package]
name = "ironrdp-pdu"
version = "0.1.0"
readme = "README.md"
description = "RDP PDU encoding and decoding"
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
authors.workspace = true
keywords.workspace = true
categories.workspace = true

[features]
default = []
std = []

[dependencies]
bitflags = "2"
tap = "1.0.1"

# TODO: get rid of these dependencies (related code should probably go into another crate)
bit_field = "0.10.2"
byteorder = "1.4.3"
der-parser = "8.2.0"
thiserror = "1.0.40"
md5 = { package = "md-5", version = "0.10.5" }
num-bigint = "0.4.3"
num-derive = "0.3.3"
num-integer = "0.1.45"
num-traits = "0.2.15"
sha1 = "0.10.5"
x509-parser = "0.15"

[dev-dependencies]
ironrdp-pdu-samples.workspace = true
lazy_static = "1.4.0"
