// <auto-generated/> by Diplomat

#pragma warning disable 0105
using System;
using System.Runtime.InteropServices;

using Interop.Diplomat;
#pragma warning restore 0105

namespace Interop;

#nullable enable

public partial class ClientConnector: IDisposable
{
    private unsafe Raw.ClientConnector* _inner;

    /// <summary>
    /// Creates a managed <c>ClientConnector</c> from a raw handle.
    /// </summary>
    /// <remarks>
    /// Safety: you should not build two managed objects using the same raw handle (may causes use-after-free and double-free).
    /// <br/>
    /// This constructor assumes the raw struct is allocated on Rust side.
    /// If implemented, the custom Drop implementation on Rust side WILL run on destruction.
    /// </remarks>
    public unsafe ClientConnector(Raw.ClientConnector* handle)
    {
        _inner = handle;
    }

    /// <returns>
    /// A <c>ClientConnector</c> allocated on Rust side.
    /// </returns>
    public static ClientConnector New(Config config)
    {
        unsafe
        {
            Raw.Config* configRaw;
            configRaw = config.AsFFI();
            if (configRaw == null)
            {
                throw new ObjectDisposedException("Config");
            }
            Raw.ClientConnector* retVal = Raw.ClientConnector.New(configRaw);
            return new ClientConnector(retVal);
        }
    }

    /// <summary>
    /// Must use
    /// </summary>
    /// <returns>
    /// A <c>ClientConnector</c> allocated on Rust side.
    /// </returns>
    public ClientConnector WithServerAddr(SocketAddr serverAddr)
    {
        unsafe
        {
            if (_inner == null)
            {
                throw new ObjectDisposedException("ClientConnector");
            }
            Raw.SocketAddr* serverAddrRaw;
            serverAddrRaw = serverAddr.AsFFI();
            if (serverAddrRaw == null)
            {
                throw new ObjectDisposedException("SocketAddr");
            }
            Raw.ClientConnector* retVal = Raw.ClientConnector.WithServerAddr(_inner, serverAddrRaw);
            return new ClientConnector(retVal);
        }
    }

    /// <summary>
    /// Returns the underlying raw handle.
    /// </summary>
    public unsafe Raw.ClientConnector* AsFFI()
    {
        return _inner;
    }

    /// <summary>
    /// Destroys the underlying object immediately.
    /// </summary>
    public void Dispose()
    {
        unsafe
        {
            if (_inner == null)
            {
                return;
            }

            Raw.ClientConnector.Destroy(_inner);
            _inner = null;

            GC.SuppressFinalize(this);
        }
    }

    ~ClientConnector()
    {
        Dispose();
    }
}
