[package]
name = "ironrdp-session"
version = "0.1.0"
edition = "2021"
readme = "README.md"
license = "MIT/Apache-2.0"
homepage = "https://github.com/Devolutions/IronRDP"
repository = "https://github.com/Devolutions/IronRDP"
authors = ["Devolutions Inc. <infos@devolutions.net>"]

[features]
default = []
rustls = ["dep:tokio-rustls"]
native-tls = ["dep:async-native-tls"]
dgw_ext = []

[dependencies]
ironrdp-pdu = { path = "../pdu" }
ironrdp-graphics = { path = "../graphics" }
ironrdp-rdcleanpath = { path = "../rdcleanpath" } # FIXME: Quick and dirty approach, this should not be here
sspi = "0.8"
bytes = "1"
tracing = "0.1.37"
whoami = "1"
semver = "1"
num-derive = "0.3.3"
num-traits = "0.2.15"
lazy_static = "1.4"
bitflags = "1"
bit_field = "0.10.1" # TODO: will be unused once the framed module is moved
byteorder = "1.4.3"
futures-util = { version = "0.3", features = ["sink", "io"] }
thiserror = "1.0.37"
rand_core = "0.6.4"
x509-cert = "0.1.0" # TODO: consider removing dependency on this one in `ironrdp-session`
async-native-tls = { version = "0.4", features = ["runtime-tokio"], default-features = false, optional = true }
tokio-rustls =  { version = "0.23", default-features = false, optional = true }
