// Bindings generated by `windows-bindgen` 0.62.1

pub mod Windows {
    pub mod Foundation {
        windows_core::imp::define_interface!(IClosable, IClosable_Vtbl, 0x30d5a829_7fa4_4026_83bb_d75bae4ea99e);
        impl windows_core::RuntimeType for IClosable {
            const SIGNATURE: windows_core::imp::ConstBuffer = windows_core::imp::ConstBuffer::for_interface::<Self>();
        }
        windows_core::imp::interface_hierarchy!(IClosable, windows_core::IUnknown, windows_core::IInspectable);
        impl IClosable {
            pub fn Close(&self) -> windows_core::Result<()> {
                let this = self;
                unsafe { (windows_core::Interface::vtable(this).Close)(windows_core::Interface::as_raw(this)).ok() }
            }
        }
        impl windows_core::RuntimeName for IClosable {
            const NAME: &'static str = "Windows.Foundation.IClosable";
        }
        pub trait IClosable_Impl: windows_core::IUnknownImpl {
            fn Close(&self) -> windows_core::Result<()>;
        }
        impl IClosable_Vtbl {
            pub const fn new<Identity: IClosable_Impl, const OFFSET: isize>() -> Self {
                unsafe extern "system" fn Close<Identity: IClosable_Impl, const OFFSET: isize>(
                    this: *mut core::ffi::c_void,
                ) -> windows_core::HRESULT {
                    unsafe {
                        let this: &Identity = &*((this as *const *const ()).offset(OFFSET) as *const Identity);
                        IClosable_Impl::Close(this).into()
                    }
                }
                Self {
                    base__: windows_core::IInspectable_Vtbl::new::<Identity, IClosable, OFFSET>(),
                    Close: Close::<Identity, OFFSET>,
                }
            }
            pub fn matches(iid: &windows_core::GUID) -> bool {
                iid == &<IClosable as windows_core::Interface>::IID
            }
        }
        #[repr(C)]
        #[doc(hidden)]
        pub struct IClosable_Vtbl {
            pub base__: windows_core::IInspectable_Vtbl,
            pub Close: unsafe extern "system" fn(*mut core::ffi::c_void) -> windows_core::HRESULT,
        }
    }
}
pub mod WindowsUdk {
    pub mod Security {
        pub mod Isolation {
            windows_core::imp::define_interface!(
                IManagedWindowsVM,
                IManagedWindowsVM_Vtbl,
                0xd65a81b9_dc23_51f5_8fbe_a1597657e5a7
            );
            impl windows_core::RuntimeType for IManagedWindowsVM {
                const SIGNATURE: windows_core::imp::ConstBuffer =
                    windows_core::imp::ConstBuffer::for_interface::<Self>();
            }
            #[repr(C)]
            #[doc(hidden)]
            pub struct IManagedWindowsVM_Vtbl {
                pub base__: windows_core::IInspectable_Vtbl,
                pub Id:
                    unsafe extern "system" fn(*mut core::ffi::c_void, *mut windows_core::GUID) -> windows_core::HRESULT,
                TerminatedReason: usize,
                TerminatedReasonChanged: usize,
                pub RemoveTerminatedReasonChanged:
                    unsafe extern "system" fn(*mut core::ffi::c_void, i64) -> windows_core::HRESULT,
                pub CreateRunningReference: unsafe extern "system" fn(
                    *mut core::ffi::c_void,
                    *mut *mut core::ffi::c_void,
                ) -> windows_core::HRESULT,
                CreateRunningReferenceWithPriority: usize,
                pub CreateRunningReferenceAsync: unsafe extern "system" fn(
                    *mut core::ffi::c_void,
                    *mut *mut core::ffi::c_void,
                ) -> windows_core::HRESULT,
                CreateRunningReferenceWithPriorityAsync: usize,
                ShareFolder: usize,
                UnshareFolder: usize,
                CreateProcessInVM: usize,
                pub GetNetworkInformation: unsafe extern "system" fn(
                    *mut core::ffi::c_void,
                    *mut core::ffi::c_void,
                    *mut *mut core::ffi::c_void,
                ) -> windows_core::HRESULT,
                pub Terminate: unsafe extern "system" fn(*mut core::ffi::c_void) -> windows_core::HRESULT,
                pub TerminateAsync: unsafe extern "system" fn(
                    *mut core::ffi::c_void,
                    *mut *mut core::ffi::c_void,
                ) -> windows_core::HRESULT,
            }
            windows_core::imp::define_interface!(
                IManagedWindowsVM2,
                IManagedWindowsVM2_Vtbl,
                0x394ca49a_cd3b_5c8d_b9a8_6ca69c8b8f36
            );
            impl windows_core::RuntimeType for IManagedWindowsVM2 {
                const SIGNATURE: windows_core::imp::ConstBuffer =
                    windows_core::imp::ConstBuffer::for_interface::<Self>();
            }
            #[repr(C)]
            #[doc(hidden)]
            pub struct IManagedWindowsVM2_Vtbl {
                pub base__: windows_core::IInspectable_Vtbl,
                pub DefaultUserName: unsafe extern "system" fn(
                    *mut core::ffi::c_void,
                    *mut *mut core::ffi::c_void,
                ) -> windows_core::HRESULT,
            }
            windows_core::imp::define_interface!(
                IManagedWindowsVM3,
                IManagedWindowsVM3_Vtbl,
                0xa589440a_f2ca_58f8_9b14_fd50652742fb
            );
            impl windows_core::RuntimeType for IManagedWindowsVM3 {
                const SIGNATURE: windows_core::imp::ConstBuffer =
                    windows_core::imp::ConstBuffer::for_interface::<Self>();
            }
            #[repr(C)]
            #[doc(hidden)]
            pub struct IManagedWindowsVM3_Vtbl {
                pub base__: windows_core::IInspectable_Vtbl,
                Storage: usize,
            }
            windows_core::imp::define_interface!(
                IManagedWindowsVMFactory,
                IManagedWindowsVMFactory_Vtbl,
                0xfdfbf323_452d_5ab3_bddc_45e90aae39c0
            );
            impl windows_core::RuntimeType for IManagedWindowsVMFactory {
                const SIGNATURE: windows_core::imp::ConstBuffer =
                    windows_core::imp::ConstBuffer::for_interface::<Self>();
            }
            #[repr(C)]
            #[doc(hidden)]
            pub struct IManagedWindowsVMFactory_Vtbl {
                pub base__: windows_core::IInspectable_Vtbl,
                pub CreateInstance: unsafe extern "system" fn(
                    *mut core::ffi::c_void,
                    *mut core::ffi::c_void,
                    *mut *mut core::ffi::c_void,
                ) -> windows_core::HRESULT,
            }
            windows_core::imp::define_interface!(
                IManagedWindowsVMFactory2,
                IManagedWindowsVMFactory2_Vtbl,
                0x480f0ba2_281f_5449_83bf_463dbdf88b6b
            );
            impl windows_core::RuntimeType for IManagedWindowsVMFactory2 {
                const SIGNATURE: windows_core::imp::ConstBuffer =
                    windows_core::imp::ConstBuffer::for_interface::<Self>();
            }
            #[repr(C)]
            #[doc(hidden)]
            pub struct IManagedWindowsVMFactory2_Vtbl {
                pub base__: windows_core::IInspectable_Vtbl,
                CreateInstance: usize,
            }
            windows_core::imp::define_interface!(
                IManagedWindowsVMStatics,
                IManagedWindowsVMStatics_Vtbl,
                0xc7dbd727_42d8_5dfc_abb1_a6ba7ed32416
            );
            impl windows_core::RuntimeType for IManagedWindowsVMStatics {
                const SIGNATURE: windows_core::imp::ConstBuffer =
                    windows_core::imp::ConstBuffer::for_interface::<Self>();
            }
            #[repr(C)]
            #[doc(hidden)]
            pub struct IManagedWindowsVMStatics_Vtbl {
                pub base__: windows_core::IInspectable_Vtbl,
                pub Open: unsafe extern "system" fn(
                    *mut core::ffi::c_void,
                    windows_core::GUID,
                    *mut *mut core::ffi::c_void,
                ) -> windows_core::HRESULT,
            }
            windows_core::imp::define_interface!(
                IVMNetworkInformation,
                IVMNetworkInformation_Vtbl,
                0x05f49bae_1a51_5f79_a3c7_e4a7eaecf118
            );
            impl windows_core::RuntimeType for IVMNetworkInformation {
                const SIGNATURE: windows_core::imp::ConstBuffer =
                    windows_core::imp::ConstBuffer::for_interface::<Self>();
            }
            #[repr(C)]
            #[doc(hidden)]
            pub struct IVMNetworkInformation_Vtbl {
                pub base__: windows_core::IInspectable_Vtbl,
                pub Mode:
                    unsafe extern "system" fn(*mut core::ffi::c_void, *mut VMNetworkingMode) -> windows_core::HRESULT,
                pub Interfaces: unsafe extern "system" fn(
                    *mut core::ffi::c_void,
                    *mut *mut core::ffi::c_void,
                ) -> windows_core::HRESULT,
            }
            windows_core::imp::define_interface!(
                IVMNetworkInterface,
                IVMNetworkInterface_Vtbl,
                0xdc1d2020_be39_5c78_9c08_10439033faa9
            );
            impl windows_core::RuntimeType for IVMNetworkInterface {
                const SIGNATURE: windows_core::imp::ConstBuffer =
                    windows_core::imp::ConstBuffer::for_interface::<Self>();
            }
            #[repr(C)]
            #[doc(hidden)]
            pub struct IVMNetworkInterface_Vtbl {
                pub base__: windows_core::IInspectable_Vtbl,
                pub Id:
                    unsafe extern "system" fn(*mut core::ffi::c_void, *mut windows_core::GUID) -> windows_core::HRESULT,
                pub IPAddresses: unsafe extern "system" fn(
                    *mut core::ffi::c_void,
                    *mut *mut core::ffi::c_void,
                ) -> windows_core::HRESULT,
            }
            windows_core::imp::define_interface!(IVMOptions, IVMOptions_Vtbl, 0xf3818e28_30bb_5256_890a_92e73b309bd6);
            impl windows_core::RuntimeType for IVMOptions {
                const SIGNATURE: windows_core::imp::ConstBuffer =
                    windows_core::imp::ConstBuffer::for_interface::<Self>();
            }
            #[repr(C)]
            #[doc(hidden)]
            pub struct IVMOptions_Vtbl {
                pub base__: windows_core::IInspectable_Vtbl,
                pub VirtualProcessorCount:
                    unsafe extern "system" fn(*mut core::ffi::c_void, *mut u32) -> windows_core::HRESULT,
                pub SetVirtualProcessorCount:
                    unsafe extern "system" fn(*mut core::ffi::c_void, u32) -> windows_core::HRESULT,
                pub MaxMemoryMB: unsafe extern "system" fn(*mut core::ffi::c_void, *mut u32) -> windows_core::HRESULT,
                pub SetMaxMemoryMB: unsafe extern "system" fn(*mut core::ffi::c_void, u32) -> windows_core::HRESULT,
                pub MaxStorageSizeMB:
                    unsafe extern "system" fn(*mut core::ffi::c_void, *mut u32) -> windows_core::HRESULT,
                pub SetMaxStorageSizeMB:
                    unsafe extern "system" fn(*mut core::ffi::c_void, u32) -> windows_core::HRESULT,
                pub DisplayName: unsafe extern "system" fn(
                    *mut core::ffi::c_void,
                    *mut *mut core::ffi::c_void,
                ) -> windows_core::HRESULT,
                pub SetDisplayName:
                    unsafe extern "system" fn(*mut core::ffi::c_void, *mut core::ffi::c_void) -> windows_core::HRESULT,
                pub NetworkingMode:
                    unsafe extern "system" fn(*mut core::ffi::c_void, *mut VMNetworkingMode) -> windows_core::HRESULT,
                pub SetNetworkingMode:
                    unsafe extern "system" fn(*mut core::ffi::c_void, VMNetworkingMode) -> windows_core::HRESULT,
                VirtualGpuOptions: usize,
                HyperVSocketServiceConfigurations: usize,
            }
            windows_core::imp::define_interface!(
                IVMRunningReference,
                IVMRunningReference_Vtbl,
                0xc66d5d54_7108_500e_816f_59dba146e2b3
            );
            impl windows_core::RuntimeType for IVMRunningReference {
                const SIGNATURE: windows_core::imp::ConstBuffer =
                    windows_core::imp::ConstBuffer::for_interface::<Self>();
            }
            #[repr(C)]
            #[doc(hidden)]
            pub struct IVMRunningReference_Vtbl {
                pub base__: windows_core::IInspectable_Vtbl,
                pub VM: unsafe extern "system" fn(
                    *mut core::ffi::c_void,
                    *mut *mut core::ffi::c_void,
                ) -> windows_core::HRESULT,
            }
            #[repr(transparent)]
            #[derive(Clone, Debug, Eq, PartialEq)]
            pub struct ManagedWindowsVM(windows_core::IUnknown);
            windows_core::imp::interface_hierarchy!(
                ManagedWindowsVM,
                windows_core::IUnknown,
                windows_core::IInspectable
            );
            impl ManagedWindowsVM {
                pub fn Id(&self) -> windows_core::Result<windows_core::GUID> {
                    let this = self;
                    unsafe {
                        let mut result__ = core::mem::zeroed();
                        (windows_core::Interface::vtable(this).Id)(windows_core::Interface::as_raw(this), &mut result__)
                            .map(|| result__)
                    }
                }
                pub fn RemoveTerminatedReasonChanged(&self, token: i64) -> windows_core::Result<()> {
                    let this = self;
                    unsafe {
                        (windows_core::Interface::vtable(this).RemoveTerminatedReasonChanged)(
                            windows_core::Interface::as_raw(this),
                            token,
                        )
                        .ok()
                    }
                }
                pub fn CreateRunningReference(&self) -> windows_core::Result<VMRunningReference> {
                    let this = self;
                    unsafe {
                        let mut result__ = core::mem::zeroed();
                        (windows_core::Interface::vtable(this).CreateRunningReference)(
                            windows_core::Interface::as_raw(this),
                            &mut result__,
                        )
                        .and_then(|| windows_core::Type::from_abi(result__))
                    }
                }
                pub fn CreateRunningReferenceAsync(
                    &self,
                ) -> windows_core::Result<windows_future::IAsyncOperation<VMRunningReference>> {
                    let this = self;
                    unsafe {
                        let mut result__ = core::mem::zeroed();
                        (windows_core::Interface::vtable(this).CreateRunningReferenceAsync)(
                            windows_core::Interface::as_raw(this),
                            &mut result__,
                        )
                        .and_then(|| windows_core::Type::from_abi(result__))
                    }
                }
                pub fn GetNetworkInformation<P0>(
                    &self,
                    runningreference: P0,
                ) -> windows_core::Result<VMNetworkInformation>
                where
                    P0: windows_core::Param<VMRunningReference>,
                {
                    let this = self;
                    unsafe {
                        let mut result__ = core::mem::zeroed();
                        (windows_core::Interface::vtable(this).GetNetworkInformation)(
                            windows_core::Interface::as_raw(this),
                            runningreference.param().abi(),
                            &mut result__,
                        )
                        .and_then(|| windows_core::Type::from_abi(result__))
                    }
                }
                pub fn Terminate(&self) -> windows_core::Result<()> {
                    let this = self;
                    unsafe {
                        (windows_core::Interface::vtable(this).Terminate)(windows_core::Interface::as_raw(this)).ok()
                    }
                }
                pub fn TerminateAsync(&self) -> windows_core::Result<windows_future::IAsyncAction> {
                    let this = self;
                    unsafe {
                        let mut result__ = core::mem::zeroed();
                        (windows_core::Interface::vtable(this).TerminateAsync)(
                            windows_core::Interface::as_raw(this),
                            &mut result__,
                        )
                        .and_then(|| windows_core::Type::from_abi(result__))
                    }
                }
                pub fn DefaultUserName(&self) -> windows_core::Result<windows_core::HSTRING> {
                    let this = &windows_core::Interface::cast::<IManagedWindowsVM2>(self)?;
                    unsafe {
                        let mut result__ = core::mem::zeroed();
                        (windows_core::Interface::vtable(this).DefaultUserName)(
                            windows_core::Interface::as_raw(this),
                            &mut result__,
                        )
                        .map(|| core::mem::transmute(result__))
                    }
                }
                pub fn CreateInstance<P0>(options: P0) -> windows_core::Result<ManagedWindowsVM>
                where
                    P0: windows_core::Param<VMOptions>,
                {
                    Self::IManagedWindowsVMFactory(|this| unsafe {
                        let mut result__ = core::mem::zeroed();
                        (windows_core::Interface::vtable(this).CreateInstance)(
                            windows_core::Interface::as_raw(this),
                            options.param().abi(),
                            &mut result__,
                        )
                        .and_then(|| windows_core::Type::from_abi(result__))
                    })
                }
                pub fn Open(id: windows_core::GUID) -> windows_core::Result<ManagedWindowsVM> {
                    Self::IManagedWindowsVMStatics(|this| unsafe {
                        let mut result__ = core::mem::zeroed();
                        (windows_core::Interface::vtable(this).Open)(
                            windows_core::Interface::as_raw(this),
                            id,
                            &mut result__,
                        )
                        .and_then(|| windows_core::Type::from_abi(result__))
                    })
                }
                fn IManagedWindowsVMFactory<R, F: FnOnce(&IManagedWindowsVMFactory) -> windows_core::Result<R>>(
                    callback: F,
                ) -> windows_core::Result<R> {
                    static SHARED: windows_core::imp::FactoryCache<ManagedWindowsVM, IManagedWindowsVMFactory> =
                        windows_core::imp::FactoryCache::new();
                    SHARED.call(callback)
                }
                fn IManagedWindowsVMFactory2<R, F: FnOnce(&IManagedWindowsVMFactory2) -> windows_core::Result<R>>(
                    callback: F,
                ) -> windows_core::Result<R> {
                    static SHARED: windows_core::imp::FactoryCache<ManagedWindowsVM, IManagedWindowsVMFactory2> =
                        windows_core::imp::FactoryCache::new();
                    SHARED.call(callback)
                }
                fn IManagedWindowsVMStatics<R, F: FnOnce(&IManagedWindowsVMStatics) -> windows_core::Result<R>>(
                    callback: F,
                ) -> windows_core::Result<R> {
                    static SHARED: windows_core::imp::FactoryCache<ManagedWindowsVM, IManagedWindowsVMStatics> =
                        windows_core::imp::FactoryCache::new();
                    SHARED.call(callback)
                }
            }
            impl windows_core::RuntimeType for ManagedWindowsVM {
                const SIGNATURE: windows_core::imp::ConstBuffer =
                    windows_core::imp::ConstBuffer::for_class::<Self, IManagedWindowsVM>();
            }
            unsafe impl windows_core::Interface for ManagedWindowsVM {
                type Vtable = <IManagedWindowsVM as windows_core::Interface>::Vtable;
                const IID: windows_core::GUID = <IManagedWindowsVM as windows_core::Interface>::IID;
            }
            impl windows_core::RuntimeName for ManagedWindowsVM {
                const NAME: &'static str = "WindowsUdk.Security.Isolation.ManagedWindowsVM";
            }
            unsafe impl Send for ManagedWindowsVM {}
            unsafe impl Sync for ManagedWindowsVM {}
            #[repr(transparent)]
            #[derive(Clone, Debug, Eq, PartialEq)]
            pub struct VMNetworkInformation(windows_core::IUnknown);
            windows_core::imp::interface_hierarchy!(
                VMNetworkInformation,
                windows_core::IUnknown,
                windows_core::IInspectable
            );
            impl VMNetworkInformation {
                pub fn Mode(&self) -> windows_core::Result<VMNetworkingMode> {
                    let this = self;
                    unsafe {
                        let mut result__ = core::mem::zeroed();
                        (windows_core::Interface::vtable(this).Mode)(
                            windows_core::Interface::as_raw(this),
                            &mut result__,
                        )
                        .map(|| result__)
                    }
                }
                pub fn Interfaces(&self) -> windows_core::Result<windows_collections::IVectorView<VMNetworkInterface>> {
                    let this = self;
                    unsafe {
                        let mut result__ = core::mem::zeroed();
                        (windows_core::Interface::vtable(this).Interfaces)(
                            windows_core::Interface::as_raw(this),
                            &mut result__,
                        )
                        .and_then(|| windows_core::Type::from_abi(result__))
                    }
                }
            }
            impl windows_core::RuntimeType for VMNetworkInformation {
                const SIGNATURE: windows_core::imp::ConstBuffer =
                    windows_core::imp::ConstBuffer::for_class::<Self, IVMNetworkInformation>();
            }
            unsafe impl windows_core::Interface for VMNetworkInformation {
                type Vtable = <IVMNetworkInformation as windows_core::Interface>::Vtable;
                const IID: windows_core::GUID = <IVMNetworkInformation as windows_core::Interface>::IID;
            }
            impl windows_core::RuntimeName for VMNetworkInformation {
                const NAME: &'static str = "WindowsUdk.Security.Isolation.VMNetworkInformation";
            }
            unsafe impl Send for VMNetworkInformation {}
            unsafe impl Sync for VMNetworkInformation {}
            #[repr(transparent)]
            #[derive(Clone, Debug, Eq, PartialEq)]
            pub struct VMNetworkInterface(windows_core::IUnknown);
            windows_core::imp::interface_hierarchy!(
                VMNetworkInterface,
                windows_core::IUnknown,
                windows_core::IInspectable
            );
            impl VMNetworkInterface {
                pub fn Id(&self) -> windows_core::Result<windows_core::GUID> {
                    let this = self;
                    unsafe {
                        let mut result__ = core::mem::zeroed();
                        (windows_core::Interface::vtable(this).Id)(windows_core::Interface::as_raw(this), &mut result__)
                            .map(|| result__)
                    }
                }
                pub fn IPAddresses(
                    &self,
                ) -> windows_core::Result<windows_collections::IVectorView<windows_core::HSTRING>> {
                    let this = self;
                    unsafe {
                        let mut result__ = core::mem::zeroed();
                        (windows_core::Interface::vtable(this).IPAddresses)(
                            windows_core::Interface::as_raw(this),
                            &mut result__,
                        )
                        .and_then(|| windows_core::Type::from_abi(result__))
                    }
                }
            }
            impl windows_core::RuntimeType for VMNetworkInterface {
                const SIGNATURE: windows_core::imp::ConstBuffer =
                    windows_core::imp::ConstBuffer::for_class::<Self, IVMNetworkInterface>();
            }
            unsafe impl windows_core::Interface for VMNetworkInterface {
                type Vtable = <IVMNetworkInterface as windows_core::Interface>::Vtable;
                const IID: windows_core::GUID = <IVMNetworkInterface as windows_core::Interface>::IID;
            }
            impl windows_core::RuntimeName for VMNetworkInterface {
                const NAME: &'static str = "WindowsUdk.Security.Isolation.VMNetworkInterface";
            }
            unsafe impl Send for VMNetworkInterface {}
            unsafe impl Sync for VMNetworkInterface {}
            #[repr(transparent)]
            #[derive(Clone, Copy, Debug, Default, Eq, PartialEq)]
            pub struct VMNetworkingMode(pub i32);
            impl VMNetworkingMode {
                pub const None: Self = Self(0i32);
                pub const Nat: Self = Self(1i32);
            }
            impl windows_core::TypeKind for VMNetworkingMode {
                type TypeKind = windows_core::CopyType;
            }
            impl windows_core::RuntimeType for VMNetworkingMode {
                const SIGNATURE: windows_core::imp::ConstBuffer = windows_core::imp::ConstBuffer::from_slice(
                    b"enum(WindowsUdk.Security.Isolation.VMNetworkingMode;i4)",
                );
            }
            #[repr(transparent)]
            #[derive(Clone, Debug, Eq, PartialEq)]
            pub struct VMOptions(windows_core::IUnknown);
            windows_core::imp::interface_hierarchy!(VMOptions, windows_core::IUnknown, windows_core::IInspectable);
            impl VMOptions {
                pub fn new() -> windows_core::Result<Self> {
                    Self::IActivationFactory(|f| f.ActivateInstance::<Self>())
                }
                fn IActivationFactory<R, F: FnOnce(&windows_core::imp::IGenericFactory) -> windows_core::Result<R>>(
                    callback: F,
                ) -> windows_core::Result<R> {
                    static SHARED: windows_core::imp::FactoryCache<VMOptions, windows_core::imp::IGenericFactory> =
                        windows_core::imp::FactoryCache::new();
                    SHARED.call(callback)
                }
                pub fn VirtualProcessorCount(&self) -> windows_core::Result<u32> {
                    let this = self;
                    unsafe {
                        let mut result__ = core::mem::zeroed();
                        (windows_core::Interface::vtable(this).VirtualProcessorCount)(
                            windows_core::Interface::as_raw(this),
                            &mut result__,
                        )
                        .map(|| result__)
                    }
                }
                pub fn SetVirtualProcessorCount(&self, value: u32) -> windows_core::Result<()> {
                    let this = self;
                    unsafe {
                        (windows_core::Interface::vtable(this).SetVirtualProcessorCount)(
                            windows_core::Interface::as_raw(this),
                            value,
                        )
                        .ok()
                    }
                }
                pub fn MaxMemoryMB(&self) -> windows_core::Result<u32> {
                    let this = self;
                    unsafe {
                        let mut result__ = core::mem::zeroed();
                        (windows_core::Interface::vtable(this).MaxMemoryMB)(
                            windows_core::Interface::as_raw(this),
                            &mut result__,
                        )
                        .map(|| result__)
                    }
                }
                pub fn SetMaxMemoryMB(&self, value: u32) -> windows_core::Result<()> {
                    let this = self;
                    unsafe {
                        (windows_core::Interface::vtable(this).SetMaxMemoryMB)(
                            windows_core::Interface::as_raw(this),
                            value,
                        )
                        .ok()
                    }
                }
                pub fn MaxStorageSizeMB(&self) -> windows_core::Result<u32> {
                    let this = self;
                    unsafe {
                        let mut result__ = core::mem::zeroed();
                        (windows_core::Interface::vtable(this).MaxStorageSizeMB)(
                            windows_core::Interface::as_raw(this),
                            &mut result__,
                        )
                        .map(|| result__)
                    }
                }
                pub fn SetMaxStorageSizeMB(&self, value: u32) -> windows_core::Result<()> {
                    let this = self;
                    unsafe {
                        (windows_core::Interface::vtable(this).SetMaxStorageSizeMB)(
                            windows_core::Interface::as_raw(this),
                            value,
                        )
                        .ok()
                    }
                }
                pub fn DisplayName(&self) -> windows_core::Result<windows_core::HSTRING> {
                    let this = self;
                    unsafe {
                        let mut result__ = core::mem::zeroed();
                        (windows_core::Interface::vtable(this).DisplayName)(
                            windows_core::Interface::as_raw(this),
                            &mut result__,
                        )
                        .map(|| core::mem::transmute(result__))
                    }
                }
                pub fn SetDisplayName(&self, value: &windows_core::HSTRING) -> windows_core::Result<()> {
                    let this = self;
                    unsafe {
                        (windows_core::Interface::vtable(this).SetDisplayName)(
                            windows_core::Interface::as_raw(this),
                            core::mem::transmute_copy(value),
                        )
                        .ok()
                    }
                }
                pub fn NetworkingMode(&self) -> windows_core::Result<VMNetworkingMode> {
                    let this = self;
                    unsafe {
                        let mut result__ = core::mem::zeroed();
                        (windows_core::Interface::vtable(this).NetworkingMode)(
                            windows_core::Interface::as_raw(this),
                            &mut result__,
                        )
                        .map(|| result__)
                    }
                }
                pub fn SetNetworkingMode(&self, value: VMNetworkingMode) -> windows_core::Result<()> {
                    let this = self;
                    unsafe {
                        (windows_core::Interface::vtable(this).SetNetworkingMode)(
                            windows_core::Interface::as_raw(this),
                            value,
                        )
                        .ok()
                    }
                }
            }
            impl windows_core::RuntimeType for VMOptions {
                const SIGNATURE: windows_core::imp::ConstBuffer =
                    windows_core::imp::ConstBuffer::for_class::<Self, IVMOptions>();
            }
            unsafe impl windows_core::Interface for VMOptions {
                type Vtable = <IVMOptions as windows_core::Interface>::Vtable;
                const IID: windows_core::GUID = <IVMOptions as windows_core::Interface>::IID;
            }
            impl windows_core::RuntimeName for VMOptions {
                const NAME: &'static str = "WindowsUdk.Security.Isolation.VMOptions";
            }
            unsafe impl Send for VMOptions {}
            unsafe impl Sync for VMOptions {}
            #[repr(transparent)]
            #[derive(Clone, Debug, Eq, PartialEq)]
            pub struct VMRunningReference(windows_core::IUnknown);
            windows_core::imp::interface_hierarchy!(
                VMRunningReference,
                windows_core::IUnknown,
                windows_core::IInspectable
            );
            windows_core::imp::required_hierarchy!(
                VMRunningReference,
                super::super::super::Windows::Foundation::IClosable
            );
            impl VMRunningReference {
                pub fn Close(&self) -> windows_core::Result<()> {
                    let this =
                        &windows_core::Interface::cast::<super::super::super::Windows::Foundation::IClosable>(self)?;
                    unsafe { (windows_core::Interface::vtable(this).Close)(windows_core::Interface::as_raw(this)).ok() }
                }
                pub fn VM(&self) -> windows_core::Result<ManagedWindowsVM> {
                    let this = self;
                    unsafe {
                        let mut result__ = core::mem::zeroed();
                        (windows_core::Interface::vtable(this).VM)(windows_core::Interface::as_raw(this), &mut result__)
                            .and_then(|| windows_core::Type::from_abi(result__))
                    }
                }
            }
            impl windows_core::RuntimeType for VMRunningReference {
                const SIGNATURE: windows_core::imp::ConstBuffer =
                    windows_core::imp::ConstBuffer::for_class::<Self, IVMRunningReference>();
            }
            unsafe impl windows_core::Interface for VMRunningReference {
                type Vtable = <IVMRunningReference as windows_core::Interface>::Vtable;
                const IID: windows_core::GUID = <IVMRunningReference as windows_core::Interface>::IID;
            }
            impl windows_core::RuntimeName for VMRunningReference {
                const NAME: &'static str = "WindowsUdk.Security.Isolation.VMRunningReference";
            }
            unsafe impl Send for VMRunningReference {}
            unsafe impl Sync for VMRunningReference {}
        }
    }
}
