[package]
name = "ironrdp-client-glutin"
version = "0.1.0"
readme = "README.md"
description = "GPU-accelerated RDP client using glutin"
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
authors.workspace = true
keywords.workspace = true
categories.workspace = true

[features]
default = ["rustls"]
rustls = ["ironrdp-tls/rustls"]
native-tls = ["ironrdp-tls/native-tls"]

[dependencies]

# Protocols
ironrdp.workspace = true
ironrdp-tls.workspace = true
sspi = { workspace = true, features = ["network_client"] }

# CLI
clap = { version = "4.2", features = ["derive", "cargo"] }
exitcode = "1.1.2"

# logging
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }

# async, futures
tokio = { version = "1", features = ["full"]}
tokio-util = { version = "0.7.7", features = ["compat"] }
futures-util = "0.3"

# Utils
chrono = "0.4.24"
anyhow = "1.0.70"

# GUI
glutin = "0.29"
ironrdp-glutin-renderer = { path = "../glutin-renderer"}
