[package]
name = "ironrdp-connector"
version = "0.10.0"
readme = "README.md"
description = "State machines to drive an RDP connection sequence"
edition.workspace = true
rust-version = "1.94"
license.workspace = true
homepage.workspace = true
repository.workspace = true
authors.workspace = true
keywords.workspace = true
categories.workspace = true

[lib]
doctest = false
test = false

[features]
default = ["rustcrypto", "legacy-crypto"]
qoi = ["ironrdp-pdu/qoi"]
qoiz = ["ironrdp-pdu/qoiz"]
legacy-crypto = ["ironrdp-pdu/legacy-crypto"]
rustcrypto = ["picky/rustcrypto", "sspi/aws-lc-rs", "sspi/legacy-protocols", "sspi/scard"]
fips-aws-lc = ["picky/fips-aws-lc", "sspi/fips"]

[dependencies]
ironrdp-svc = { path = "../ironrdp-svc", version = "0.8" } # public
ironrdp-core = { path = "../ironrdp-core", version = "0.2" } # public
ironrdp-error = { path = "../ironrdp-error", version = "0.2" } # public
ironrdp-pdu = { path = "../ironrdp-pdu", version = "0.9", default-features = false, features = ["std"] } # public
sspi = { version = "0.21.3", default-features = false }
url = "2.5" # public
rand = { version = "0.9", features = ["std"] } # TODO: dependency injection?
tracing = { version = "0.1", features = ["log"] }
picky-asn1-der = "0.5"
picky-asn1-x509 = "0.15"
picky = { version = "=7.0.0-rc.25", default-features = false }

[lints]
workspace = true
