export * as default from './iron-remote-desktop.svelte';
export type { ResizeEvent } from './interfaces/ResizeEvent';
export type { NewSessionInfo } from './interfaces/NewSessionInfo';
export type { IronError, IronErrorKind, RDCleanPathDetails } from './interfaces/Error';
export type { SessionTerminationInfo } from './interfaces/SessionTerminationInfo';
export type { ClipboardData } from './interfaces/ClipboardData';
export type { ClipboardItem } from './interfaces/ClipboardItem';
export type { DeviceEvent } from './interfaces/DeviceEvent';
export type { InputTransaction } from './interfaces/InputTransaction';
export type { Session } from './interfaces/Session';
export type { SessionBuilder } from './interfaces/SessionBuilder';
export type { DesktopSize } from './interfaces/DesktopSize';
export type { UserInteraction } from './interfaces/UserInteraction';
export type { FileTransferProvider } from './interfaces/FileTransferProvider';
export { Config } from './services/Config';
export { ConfigBuilder } from './services/ConfigBuilder';
