[package]
name = "ironrdp-replay-client"
version = "0.1.0"
readme = "README.md"
description = "Utility tool to replay RDP graphics pipeline for debugging purposes"
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
authors.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
ironrdp.workspace = true
ironrdp-glutin-renderer = { path = "../glutin-renderer" }
clap = { version = "4.2", features = ["derive", "cargo"] }
glutin = { version = "0.30" }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }
