#![doc = include_str!("../README.md")]
#![doc(html_logo_url = "https://cdnweb.devolutions.net/images/projects/devolutions/logos/devolutions-icon-shadow.svg")]
#![allow(clippy::new_without_default)] // Default trait can’t be used by wasm consumer anyway
#![allow(unsafe_op_in_unsafe_fn)] // We can’t control code generated by `wasm-bindgen`

// Silence the unused_crate_dependencies lint
// These crates are added just to enable additional WASM features
extern crate chrono as _;
extern crate getrandom as _;
extern crate time as _;

#[macro_use]
extern crate tracing;

use iron_remote_desktop::export_wasm;

mod canvas;
mod clipboard;
mod error;
mod image;
mod input;
mod network_client;
mod session;

fn iron_init(log_level: &str) {
    iron_remote_desktop::iron_init(log_level);

    debug!("IronRDP is ready");
}

export_wasm!(
    crate::iron_init,
    crate::session::RdpSession,
    crate::session::RdpSessionBuilder,
    crate::session::RdpSessionTerminationInfo,
    crate::input::RdpDeviceEvent,
    crate::input::RdpInputTransaction,
    crate::clipboard::RdpClipboardTransaction,
    crate::clipboard::RdpClipboardContent,
    crate::error::RdpIronError
);
