#![doc = include_str!("../README.md")]
#![doc(html_logo_url = "https://cdnweb.devolutions.net/images/projects/devolutions/logos/devolutions-icon-shadow.svg")]
#![allow(clippy::new_without_default)] // Default trait can’t be used by wasm consumer anyway
#![allow(unsafe_op_in_unsafe_fn)] // We can’t control code generated by `wasm-bindgen`

// Silence the unused_crate_dependencies lint
// These crates are added just to enable additional WASM features
extern crate chrono as _;
extern crate getrandom as _;
extern crate time as _;

// Required by wasm-bindgen-derive crate
extern crate alloc;

#[macro_use]
extern crate tracing;

use iron_remote_desktop::RemoteDesktopApi;

mod canvas;
mod clipboard;
mod error;
mod extension;
mod image;
mod input;
mod network_client;
mod session;

struct Api;

impl RemoteDesktopApi for Api {
    type Session = session::Session;
    type SessionBuilder = session::SessionBuilder;
    type SessionTerminationInfo = session::SessionTerminationInfo;
    type DeviceEvent = input::DeviceEvent;
    type InputTransaction = input::InputTransaction;
    type ClipboardTransaction = clipboard::RdpClipboardTransaction;
    type ClipboardContent = clipboard::RdpClipboardContent;
    type Error = error::IronError;
}

#[doc(hidden)]
pub mod internal {
    #[allow(dead_code)]
    fn iron_init(log_level: &str) {
        iron_remote_desktop::iron_init(log_level);

        debug!("IronRDP is ready");
    }
}

iron_remote_desktop::export!(crate::Api);
