[package]
name = "ironrdp-session-async"
version = "0.1.0"
readme = "README.md"
description = "Provides `Future`s wrapping the RDP session state machines conveniently"
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
authors.workspace = true
keywords.workspace = true
categories.workspace = true

[features]
default = ["tokio"]
tokio = ["dep:tokio", "dep:tokio-util"]
futures = ["dep:futures-util"]

[dependencies]
ironrdp-pdu.workspace = true
ironrdp-session.workspace = true
bytes = "1"
num-traits = "0.2.15"
bit_field = "0.10.2"
byteorder = "1.4.3"
tokio = { version = "1.27.0", features = ["io-util"], optional = true }
tokio-util = { version = "0.7.7", features = ["codec"], optional = true }
futures-util = { version = "0.3.28", features = ["io"], optional = true }
