[package]
name = "ironrdp-rdcleanpath"
version = "0.1.0"
readme = "README.md"
description = "RDCleanPath PDU structure used by IronRDP web client and Devolutions Gateway"
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
authors.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
der = { version = "0.6.0", features = ["alloc", "derive"] }
bytes = "1.3.0"

[dev-dependencies]
rstest = "0.15.0"
hex = "0.4.3"
pretty_assertions = "1.3.0"
