[package]
name = "app"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
license = ""
repository = ""
default-run = "app"
edition = "2021"
rust-version = "1.59"

[features]
# by default Tauri runs in production mode
# when `tauri dev` runs it is executed with `cargo run --no-default-features` if `devPath` is an URL
default = [ "custom-protocol" ]
# this feature is used for production builds where `devPath` points to the filesystem
# DO NOT remove this
custom-protocol = [ "tauri/custom-protocol" ]

[dependencies]

# Protocol
ironrdp = { path = "../../ironrdp" }
sspi = { version = "0.8", features = ["network_client"] }
serde = { version = "1.0", features = ["derive"] }

# SSL
x509-parser = "0.14"
rustls = { version = "0.20", features = ["dangerous_configuration"] }

# async, futures
tokio = { version = "1", features = ["full"] }
tokio-rustls =  "0.23"
tokio-util = { version = "0.7.4", features = ["compat"] }
tokio-tungstenite = "0.17.2"
futures-util = "0.3.25"

# utils
anyhow = "1"
bytes = "1"

# tauri stuff
tauri = { version = "1.2.0", features = [] }

[workspace]
members = ["."]

[build-dependencies]
tauri-build = { version = "1.2.0", features = [] }

