# Prettier:
# - https://prettier.io/docs/en/options
---
useTabs: false
tabWidth: 4
singleQuote: true
semi: true
trailingComma: all
printWidth: 120
endOfLine: crlf

overrides:
  - files:
      - '*.yml'
      - '*.yaml'
      - '*.json'
      - '*.html'
      - '*.md'
    options:
      tabWidth: 2
