[package]
name = "ironrdp-testsuite-core"
version = "0.0.0"
edition = "2021"
description = "IronRDP test suite"
publish = false
autotests = false

[lib]
doctest = false
test = false

[[test]]
name = "integration_tests_core"
path = "tests/main.rs"
harness = true

[dependencies]
array-concat = "0.5"
expect-test = "1"
ironrdp-core.path = "../ironrdp-core"
ironrdp-pdu.path = "../ironrdp-pdu"
lazy_static.workspace = true # TODO: remove in favor of https://doc.rust-lang.org/std/sync/struct.OnceLock.html
paste = "1"

[dev-dependencies]
anyhow = "1"
expect-test.workspace = true
hex = "0.4"
ironrdp-cliprdr-format.path = "../ironrdp-cliprdr-format"
ironrdp-cliprdr.path = "../ironrdp-cliprdr"
ironrdp-connector.path = "../ironrdp-connector"
ironrdp-displaycontrol.path = "../ironrdp-displaycontrol"
ironrdp-dvc.path = "../ironrdp-dvc"
ironrdp-fuzzing.path = "../ironrdp-fuzzing"
ironrdp-graphics.path = "../ironrdp-graphics"
ironrdp-input.path = "../ironrdp-input"
ironrdp-rdcleanpath.path = "../ironrdp-rdcleanpath"
ironrdp-rdpsnd.path = "../ironrdp-rdpsnd"
ironrdp-session.path = "../ironrdp-session"
png = "0.17"
pretty_assertions = "1.4"
proptest.workspace = true
rstest.workspace = true

[lints]
workspace = true
