[package]
name = "ironrdp-testsuite-core"
version = "0.0.0"
edition = "2021"
description = "IronRDP test suite"
publish = false
autotests = false

[lib]
doctest = false
test = false

[[test]]
name = "integration_tests_core"
path = "tests/main.rs"
harness = true

[dependencies]
array-concat = "0.5"
ironrdp-pdu.workspace = true
lazy_static.workspace = true # TODO: remove in favor of https://doc.rust-lang.org/std/sync/struct.OnceLock.html
paste = "1"

[dev-dependencies]
png = "0.17"
hex = "0.4"
ironrdp-cliprdr.workspace = true
ironrdp-cliprdr-format.workspace = true
ironrdp-connector.workspace = true
ironrdp-dvc.workspace = true
ironrdp-fuzzing.workspace = true
ironrdp-graphics.workspace = true
ironrdp-input.workspace = true
ironrdp-rdcleanpath.workspace = true
ironrdp-rdpsnd.workspace = true
ironrdp-session.workspace = true
ironrdp-displaycontrol.workspace = true
pretty_assertions = "1.4"
proptest.workspace = true
rstest.workspace = true
expect-test.workspace = true
anyhow = "1"
