[package]
name = "ironrdp-testsuite-core"
version = "0.0.0"
edition = "2021"
description = "IronRDP test suite."
publish = false
autotests = false

[lib]
doctest = false
test = false

[[test]]
name = "integration_tests_core"
path = "tests/main.rs"
harness = true

[dependencies]
ironrdp-pdu.workspace = true
ironrdp-graphics.workspace = true
arbitrary = { version = "1", features = ["derive"] }
anyhow = "1"
array-concat = "0.5.2"
lazy_static = "1.4.0"
paste = "1"

[dev-dependencies]
ironrdp-connector.workspace = true
ironrdp-session.workspace = true
ironrdp-input.workspace = true
ironrdp-rdcleanpath.workspace = true
proptest.workspace = true
rstest.workspace = true
hex = "0.4.3"
pretty_assertions = "1.3.0"
rdp-rs = { git = "https://github.com/citronneur/rdp-rs", rev = "7ac880d7efb7f05efef3c84476f7c24f4053e0ea" }

