[package]
name = "ironrdp-wasm"
version = "0.1.0"
authors = ["Benoît CORTIER <bcortier@proton.me>"]
edition = "2018"

[lib]
name = "ironrdp"
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error_panic_hook"]

[workspace]
members = ["."]

[dependencies]
wasm-bindgen = "0.2.83"
wasm-bindgen-futures = "0.4.33"
lazy_static = "1.4.0"
ron = "0.8.0"
serde = { version = "1.0.147", features = ["derive"] }
ironrdp = { path = "../../ironrdp" }
ironrdp-session = { path = "../../ironrdp-session" }

# The `console_error_panic_hook` crate provides better debugging of panics by
# logging them with `console.error`. This is great for development, but requires
# all the `std::fmt` and `std::panicking` infrastructure, so isn't great for
# code size when deploying.
console_error_panic_hook = { version = "0.1.7", optional = true }

# Enable WebAssembly support for getrandom
getrandom = { version = "*", features = ["js"] }

[dev-dependencies]
wasm-bindgen-test = "0.3.33"

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
