[package]
name = "ironrdp-replay-client"
version = "0.1.0"
readme = "README.md"
description = "Utility tool to replay RDP graphics pipeline for debugging purposes"
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
authors.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
ironrdp.workspace = true
ironrdp-glutin-renderer.workspace = true
tracing.workspace = true
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
clap = { version = "4.2", features = ["derive", "cargo"] }
glutin = { version = "0.29" }

[lints]
workspace = true

