[package]
name = "ironrdp-rdpdr-native"
version = "0.7.0"
readme = "README.md"
description = "Native RDPDR static channel backend implementations for IronRDP"
edition.workspace = true
rust-version = "1.94"
license.workspace = true
homepage.workspace = true
repository.workspace = true
authors.workspace = true
keywords.workspace = true
categories.workspace = true

[lib]
doctest = false

[target.'cfg(any(target_os = "macos", target_os = "linux"))'.dependencies]
ironrdp-core = { path = "../ironrdp-core", version = "0.2" }
ironrdp-pdu = { path = "../ironrdp-pdu", version = "0.9" } # public
ironrdp-svc = { path = "../ironrdp-svc", version = "0.8" } # public
ironrdp-rdpdr = { path = "../ironrdp-rdpdr", version = "0.7" } # public
nix = { version = "0.31", features = ["fs", "dir"] }
tracing = { version = "0.1", features = ["log"] }

[target.'cfg(windows)'.dependencies]
ironrdp-core = { path = "../ironrdp-core", version = "0.2" }
ironrdp-pdu = { path = "../ironrdp-pdu", version = "0.9" }
ironrdp-rdpdr = { path = "../ironrdp-rdpdr", version = "0.7" }
ironrdp-svc = { path = "../ironrdp-svc", version = "0.8" }
tracing = { version = "0.1", features = ["log"] }
windows = { version = "0.62", features = [
    "Wdk_Foundation",
    "Wdk_Storage_FileSystem",
    "Wdk_System_SystemServices",
    "Win32_Foundation",
    "Win32_Security",
    "Win32_Security_Authorization",
    "Win32_Storage_FileSystem",
    "Win32_System_IO",
    "Win32_System_Threading",
] }

[lints]
workspace = true
