[package]
name = "ironrdp-testsuite-extra"
version = "0.1.0"
edition.workspace = true
description = "IronRDP extra test suite"
publish = false
license.workspace = true
homepage.workspace = true
repository.workspace = true
authors.workspace = true
keywords.workspace = true
categories.workspace = true

[dev-dependencies]
anyhow = "1.0"
async-trait = "0.1"
ironrdp = { path = "../ironrdp", features = ["server", "pdu", "connector", "session", "connector"] }
ironrdp-async.path = "../ironrdp-async"
ironrdp-tokio.path = "../ironrdp-tokio"
ironrdp-tls = { path = "../ironrdp-tls", features = ["rustls"] }
semver = "1.0"
tracing = { version = "0.1", features = ["log"] }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tokio = { version = "1", features = ["sync", "time"] }

[lints]
workspace = true
