[package]
name = "ironrdp-rpc"
version = "0.1.0"
publish = false
readme = "README.md"
description = "Shared local RPC protocol and transport for IronRDP clients"
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
authors.workspace = true
keywords.workspace = true
categories.workspace = true

[features]
# Internal (PRIVATE!) feature used to expose codec helpers to the shared integration tests.
# Don't rely on this whatsoever. It may disappear at any time.
__test = []

[dependencies]
ironrdp-core = { path = "../ironrdp-core", version = "0.3", features = ["alloc"] } # public
ironrdp-input = { path = "../ironrdp-input", version = "0.7" } # public
ironrdp-pdu = { path = "../ironrdp-pdu", version = "0.10" }
ironrdp-propertyset = { path = "../ironrdp-propertyset", version = "0.1" } # public
tokio = { version = "1", features = ["net", "io-util"] }
anyhow = "1"
ironrdp-rdpei = { version = "0.1.0", path = "../ironrdp-rdpei" } # public

[target.'cfg(unix)'.dependencies]
libc = "0.2"

[target.'cfg(windows)'.dependencies]
tracing = "0.1"
whoami = "2.1"
windows = { version = "0.62", features = [
    "Win32_Foundation",
    "Win32_Security",
    "Win32_Security_Authorization",
    "Win32_System_Threading",
] }

[dev-dependencies]
tokio = { version = "1", features = ["macros", "rt"] }

[lints]
workspace = true
