<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <AssemblyName>ironrdp-axhost</AssemblyName>
    <RootNamespace>IronRdpAxHost</RootNamespace>
  </PropertyGroup>
</Project>
